title: DevConf Jekyll Template for multiple events
description: >- # this means to ignore newlines until "baseurl:"
  Customizable Jekyll theme that allows you to create multiple events.
baseurl: "/DevConf-Jekyll-Theme" # the subpath of your site, e.g. /blog
url: "https://la-rebelion.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: AdES_MX
github_username:  la-rebelion
encoding: "utf-8"

author: Rebelion Labs
navigation-header: true

footer:
  # how to contact in the footer
  contact:
    email: viva@rebelion.la
    twitter: AdES_MX
    instagram: "#"
    youtube: "#"
  # policies and terms
  links:
    - text: Code of Conduct
      link: "#"
    - text: Terms
      link: "#"
    - text: Privacy
      link: "#"

# Tracker
### Analytics ###
analytics:
  enabled: true                                        # Set true to enable analytics
  google:
    tracking_id: ""

# Build settings
compress-site: yes

# Build settings
#theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
